import java.util.*;

class Translator {
// translates normal text into alig text

Hashtable words,phrases;
boolean switch1;

public String translateWord(String w) {
  if (w.length()<3) return w;
  String punctuation="";
  //strip puncuation
  for (int i=3;i<w.length();i++) {
    if (!(((w.charAt(i)>='a') && (w.charAt(i)<='z')) || ((w.charAt(i)>='A') && (w.charAt(i)<='Z')) || (w.charAt(i)=='\''))) {
      punctuation=w.substring(i,w.length());
      w=w.substring(0,i);
      break;
    }
  }
  
  //replace word or stems
  if (words.containsKey(w)) {
    w = (String)words.get(w);
  } else if ((w.indexOf("ing")==w.length()-3)&&(words.containsKey(w.substring(0,w.length()-3)))) {
    w = (String)words.get(w.substring(0,w.length()-3))+"in";
  } else if ((w.indexOf("en")==w.length()-2)&&(words.containsKey(w.substring(0,w.length()-2))))  {
    w = (String)words.get(w.substring(0,w.length()-2))+"en";
  } else if ((w.indexOf("'s")==w.length()-2)&&(words.containsKey(w.substring(0,w.length()-2))))  {
    w = (String)words.get(w.substring(0,w.length()-2))+"'s";
  } else if ((w.indexOf("s")==w.length()-1)&&(words.containsKey(w.substring(0,w.length()-1))))  {
    w = (String)words.get(w.substring(0,w.length()-1))+"s";
  }
  return changeSpelling(w)+changePunctuation(punctuation,w.length()%3);
}

public String translateSentence(String s) {
  s=s.toLowerCase();
  // translate phrases
  int pos=0;
  String key="",value="";
  for (Enumeration e=phrases.keys();e.hasMoreElements();) {
    key=(String)e.nextElement();
    pos=s.indexOf(key);
    if (pos>-1) {
      value=(String)phrases.get((Object)key);
      s=s.substring(0,pos)+value+s.substring(pos+key.length(),s.length());
    }
  }
  StringTokenizer T = new StringTokenizer(s);
  s="";
  while (T.hasMoreTokens()) {
    s=s+translateWord(T.nextToken())+" ";
  }
  return s;
}

private String changeSpelling(String w) {
  try {
    if (w.indexOf("ing")==w.length()-3) w=w.substring(0,w.length()-3)+"in";
    if (w.indexOf("th")==w.length()-2) w=w.substring(0,w.length()-2)+"f";
    if (w.indexOf("en")==w.length()-2) w=w.substring(0,w.length()-2)+"un";
    if (w.indexOf("er")==w.length()-2) w=w.substring(0,w.length()-2)+"a";
    if (w.indexOf("or")==w.length()-2) w=w.substring(0,w.length()-2)+"a";
    if (w.indexOf("h")==0) w=w.substring(1,w.length());
  } catch (StringIndexOutOfBoundsException e) {}
  if (w.length()>8) {
    for (int i=5;i<w.length()-5;i++) {
      try {
        char[] c1={w.charAt(i),w.charAt(i+1),w.charAt(i+2),w.charAt(i+3),w.charAt(i+4)};
        if ((isVowel(c1[0]))&&(isConsonant(c1[1]))&&(isVowel(c1[2]))&&(isConsonant(c1[3]))&&(isVowel(c1[4]))) {
          w=w.substring(0,i)+c1[0]+c1[3]+c1[2]+c1[1]+c1[4]+w.substring(i+5,w.length());
          break;
        }
      } catch (StringIndexOutOfBoundsException e) {}
    }
  }
          
  return w;
}

private boolean isVowel(char c) {
  return ((c=='a')||(c=='e')||(c=='i')||(c=='o')||(c=='u'));
}

private boolean isConsonant(char c) {
  return ((c>='a')&&(c<='z')&&(!isVowel(c)));
}

private String changePunctuation(String p,int r) {
  Random rand = new Random(r);
  String p2="";
  for (int i=0;i<p.length();i++) {
    if ((p.charAt(i)=='!')&&(rand.nextInt()%3>0)) {
      p2=p2+", boyakasha!";
    } else if ((p.charAt(i)=='?')&&(rand.nextInt()%3>0)) {
      p2=p2+". Is it becoz I is black?";
    } else {
      p2=p2+p.charAt(i);
    }
  }
  return p2;
}

public Translator() {
words=new Hashtable();
phrases=new Hashtable();


words.put("absent" , "not in da house");
words.put("absolutely" , "for real");
words.put("actual" , "hactual");
words.put("adolescant" , "half bush");
words.put("adolescence" , "half bush");
words.put("agent" , "asian");
words.put("alright" , "aight");
words.put("am" , "is");
words.put("an" , "a");
words.put("anal" , "batty");
words.put("angry" , "menstural");
words.put("animal" , "aminal");
words.put("annoying" , "pissin");
words.put("anus" , "batty");
words.put("apartment" , "turf");
words.put("are" , "is");
words.put("argument" , "ruk");
words.put("arguments" , "ruks");
words.put("arse" , "batty");
words.put("arse" , "exit");
words.put("arsehole" , "batty hole");
words.put("ass" , "batty");
words.put("asses" , "batties");
words.put("asshole" , "batty hole");
words.put("attractive" , "fit");
words.put("austria" , "Newgoslavia");
words.put("awful" , "mingin");
words.put("babe" , "fit bitch");
words.put("baby" , "bitch");
words.put("bad" , "wicked");
words.put("ballix" , "balls");
words.put("balls" , "biggies");
words.put("balls" , "mr biggies");
words.put("bang" , "bone");
words.put("banged" , "boned");
words.put("barn" , "farm");
words.put("bastard" , "bastid");
words.put("bbc" , "telly");
words.put("beast" , "mr biggy");
words.put("beautiful" , "wicked");
words.put("because" , "coz");
words.put("bedsit" , "turf");
words.put("been" , "bin");
words.put("bent" , "batty");
words.put("best" , "fittest");
words.put("best" , "wickedest");
words.put("bestfriend" , "main man");
words.put("bestfriend" , "main man");
words.put("big" , "massiv");
words.put("billion" , "quillion");
words.put("bird" , "bitch");
words.put("bird" , "bitch");
words.put("birds" , "bitches");
words.put("bisexual" , "trisexual");
words.put("bisexual" , "trisexual");
words.put("bizarre" , "batty");
words.put("blacks" , "bruvers");
words.put("bloke" , "geezer");
words.put("blonde" , "fit");
words.put("blow" , "erbal remedy");
words.put("bollox" , "balls");
words.put("boob" , "babylon");
words.put("bored" , "chilled");
words.put("borrow" , "steal");
words.put("boss" , "main man");
words.put("bottom" , "batty");
words.put("boyfriend" , "main man");
words.put("boys" , "bruvers");
words.put("boys" , "main men");
words.put("break" , "chill");
words.put("breast" , "babylon");
words.put("brill" , "wicked");
words.put("brilliant" , "wicked");
words.put("brother" , "bruver");
words.put("browse" , "check");
words.put("bugger" , "bum");
words.put("bum" , "batty");
words.put("bumfuck" , "bum");
words.put("bumhole" , "batty hole");
words.put("bunch" , "crew");
words.put("butt" , "batty");
words.put("butt" , "batty");
words.put("butthole" , "batty hole");
words.put("buy" , "purchase");
words.put("bye" , "bo");
words.put("cane" , "erbal remedy");
words.put("cannabis" , "erbal remedy");
words.put("cap" , "tommy");
words.put("car" , "auto");
words.put("cat" , "aminal");
words.put("catholic" , "muslim");
words.put("catholics" , "muslims");
words.put("center" , "house");
words.put("centre" , "house");
words.put("certainly" , "aye");
words.put("cheese" , "erbal remedy");
words.put("chick" , "bitch");
words.put("chicken" , "chikun");
words.put("chilled" , "ambient");
words.put("chum" , "main man");
words.put("chums" , "boys");
words.put("cigarette" , "fag");
words.put("city" , "turf");
words.put("clever" , "brainiest");
words.put("click" , "let it rip");
words.put("clit" , "love button");
words.put("clitoris" , "love button");
words.put("clockwork" , "chocolate");
words.put("clothes" , "threads");
words.put("club" , "cukabilly");
words.put("coat" , "tommy hilfinger");
words.put("cocaine" , "erbal remedy");
words.put("cock" , "dong");
words.put("coins" , "coppers");
words.put("coke" , "craic");
words.put("colleage" , "main man");
words.put("colleages" , "boys");
words.put("college" , "scool");
words.put("commies" , "nazies");
words.put("commy" , "nazy");
words.put("company" , "crew");
words.put("compliment" , "respect");
words.put("compliments" , "respects");
words.put("computer" , "pooter");
words.put("condom" , "rubber");
words.put("conservative" , "constervative");
words.put("constabulary" , "constalubury");
words.put("cool" , "wicked");
words.put("coolest" , "fittest");
words.put("coppers" , "pigs");
words.put("cops" , "constalubury");
words.put("country" , "turf");
words.put("cow" , "bitch");
words.put("coworker" , "main man");
words.put("coworkers" , "boys");
words.put("craic" , "crack");
words.put("crap" , "mingin");
words.put("crapper" , "bog");
words.put("cunning" , "brainiest");
words.put("cunt" , "punanni");
words.put("curse" , "say a swear word");
words.put("cursed" , "sed swear words");
words.put("curses" , "sez swear words");
words.put("cursing" , "saying swear words");
words.put("cute" , "fit");
words.put("dad" , "old geezer");
words.put("darlin" , "bitch");
words.put("darling" , "bitch");
words.put("dead" , "stiff");
words.put("definitely" , "for real");
words.put("depressed" , "down");
words.put("dick" , "dong");
words.put("dickhead" , "chief");
words.put("dinner" , "grub");
words.put("dinnertime" , "grubtime");
words.put("dirty" , "mingin");
words.put("discover" , "check");
words.put("discrimination" , "racalist");
words.put("dislike" , "don't dig");
words.put("dj" , "selecta");
words.put("document" , "bit of paper");
words.put("dodgy" , "batty");
words.put("dog" , "aminal");
words.put("dong" , "knob");
words.put("dope" , "erbal remedy");
words.put("dozen" , "quillion");
words.put("draw" , "erbal remedy");
words.put("drug" , "erbal remedy");
words.put("drugs" , "erbal remedies");
words.put("drunk" , "a little bit ratted");
words.put("dude" , "man");
words.put("dumass" , "chief");
words.put("dyke" , "feminist");
words.put("employee" , "main man");
words.put("enemies" , "emenies");
words.put("enemy" , "emeny");
words.put("enjoy" , "chill");
words.put("enjoy" , "dig");
words.put("enormous" , "maximum");
words.put("enter" , "let it rip");
words.put("erection" , "bone");
words.put("especially" , "for real");
words.put("everybody" , "me crew");
words.put("exact" , "pacific");
words.put("exactly" , "pacifically");
words.put("examine" , "check");
words.put("excellent" , "wicked");
words.put("exceptional" , "fore real");
words.put("exhausted" , "wrecked");
words.put("explore" , "check");
words.put("fag" , "batty boy");
words.put("faggot" , "batty boy");
words.put("faggott" , "batty boy");
words.put("family" , "crew");
words.put("fancy" , "dig");
words.put("fanny" , "flange");
words.put("fantastic" , "wicked");
words.put("fart" , "trumpet");
words.put("farts" , "trumpets");
words.put("fat" , "large");
words.put("father" , "old geezer");
words.put("favorite" , "bestest");
words.put("favour" , "dig");
words.put("favourite" , "bestest");
words.put("feet" , "feets");
words.put("female" , "bitch");
words.put("females" , "bitches");
words.put("fenian" , "muslim");
words.put("fight" , "ruk");
words.put("fights" , "ruks");
words.put("filthy" , "mingin");
words.put("find" , "check");
words.put("fine" , "wicked");
words.put("finest" , "fittest");
words.put("flat" , "turf");
words.put("folk" , "geezers");
words.put("food" , "grub");
words.put("fool" , "batty boy");
words.put("foot" , "foots");
words.put("fox" , "lady");
words.put("freak" , "bitch");
words.put("friend" , "main man");
words.put("friends" , "boys");
words.put("fuck" , "ride the punanni");
words.put("fucking" , "riding the punanni");
words.put("fucking" , "well");
words.put("full" , "maximum");
words.put("fun" , "wicked");
words.put("funniest" , "wickedist");
words.put("funny" , "wicked");
words.put("gaelic" , "gay lick");
words.put("gailic" , "gay lick");
words.put("gang" , "crew");
words.put("ganja" , "erbal remedy");
words.put("gaol" , "inside");
words.put("gape" , "check");
words.put("gay" , "batty boy");
words.put("gays" , "batty boys");
words.put("gaze" , "check");
words.put("gear" , "erbal remedy");
words.put("gift" , "pressie");
words.put("gigantic" , "massiv");
words.put("girl" , "bitch");
words.put("girlfriend" , "bitch");
words.put("girls" , "bitches");
words.put("give" , "borrow");
words.put("glance" , "check");
words.put("glasses" , "yellow sunglasses");
words.put("god" , "Jackie Chan");
words.put("good" , "wicked");
words.put("goodbye" , "bo");
words.put("good-bye" , "bo");
words.put("goodlooking" , "fit");
words.put("goods" , "goods");
words.put("gorgeous" , "fit");
words.put("gran" , "nan");
words.put("grandmother" , "nan");
words.put("granny" , "nan");
words.put("grass" , "erbal remedy");
words.put("great" , "wicked");
words.put("greece" , "Newgoslavia");
words.put("greeting" , "hear me now");
words.put("greetings" , "hear me now");
words.put("groovy" , "wicked");
words.put("guy" , "boy");
words.put("guy" , "geezer");
words.put("hairy" , "mingin");
words.put("handsome" , "wicked");
words.put("happy" , "chilled");
words.put("hash" , "erbal remedy");
words.put("hashish" , "erbal remedy");
words.put("hassle" , "aggro");
words.put("hate" , "don't dig");
words.put("hated" , "rank");
words.put("hello" , "alo");
words.put("here" , "ere");
words.put("here" , "in da house");
words.put("heroin" , "gear");
words.put("hi" , "alo");
words.put("hiphop" , "speed garage");
words.put("his" , "is");
words.put("hiya" , "alo");
words.put("hole" , "batty");
words.put("home" , "turf");
words.put("home" , "westside");
words.put("homosapien" , "homosexual");
words.put("homosexual" , "homosapien");
words.put("homosexuals" , "homosapiens");
words.put("honey" , "bitch");
words.put("honker" , "babylon");
words.put("hooker" , "ho");
words.put("hooter" , "babylon");
words.put("horrible" , "mingin");
words.put("horse" , "aminal");
words.put("hospital" , "hostipal");
words.put("hot" , "spunky");
words.put("hows" , "how is");
words.put("how's" , "how is");
words.put("huge" , "massiv");
words.put("humped" , "boned");
words.put("humps" , "bones");
words.put("hundred" , "quillion");
words.put("hungary" , "Newgoslavia");
words.put("hunt" , "check");
words.put("hurt" , "is wrecked");
words.put("i" , "me");
words.put("idiot" , "chief");
words.put("im" , "i is");
words.put("i'm" , "me is");
words.put("in" , "on");
words.put("indie" , "speed garage");
words.put("individual" , "main man");
words.put("inspect" , "check");
words.put("inspect" , "check");
words.put("insult" , "dis");
words.put("insulted" , "dissed");
words.put("insulting" , "dissing");
words.put("insults" , "disses");
words.put("intelligent" , "brainiest");
words.put("investigate" , "check");
words.put("irish" , "sound");
words.put("is" , "is");
words.put("italy" , "Newgoslavia");
words.put("jail" , "inside");
words.put("jazz" , "speed garage");
words.put("jeep" , "auto");
words.put("jesus" , "Jackie Chan");
words.put("joint" , "spliff");
words.put("jump" , "hop");
words.put("jumped" , "hopped");
words.put("keen" , "wicked");
words.put("king" , "main man");
words.put("knob" , "dong");
words.put("lad" , "main man");
words.put("ladies" , "bitches");
words.put("lady" , "bitch");
words.put("land" , "turf");
words.put("langer" , "dong");
words.put("language" , "lingo");
words.put("large" , "massiv");
words.put("lav" , "bog");
words.put("lavatory" , "bog");
words.put("law" , "pigs");
words.put("lend" , "borrow");
words.put("lesbian" , "feminist");
words.put("lesbianism" , "feminism");
words.put("like" , "dig");
words.put("loads" , "quillions");
words.put("loo" , "bog");
words.put("look" , "check");
words.put("loose" , "chill");
words.put("lots" , "quillions");
words.put("love" , "dig");
words.put("lovely" , "wicked");
words.put("lover" , "bitch");
words.put("lunch" , "grub");
words.put("lunchtime" , "grubtime");
words.put("luv" , "bitch");
words.put("man" , "geezer");
words.put("manager" , "main man");
words.put("marajuana" , "erbal remedy");
words.put("marijuana" , "erbal remedy");
words.put("massive" , "massiv");
words.put("masturbate" , "crack one off");
words.put("masturbated" , "cracked one off");
words.put("masturbates" , "cracks one off");
words.put("masturbating" , "cracking one off");
words.put("mate" , "main man");
words.put("mates" , "boys");
words.put("matey" , "main man");
words.put("mature" , "full bush");
words.put("melon" , "babylon");
words.put("men" , "bruvers");
words.put("millenium" , "minnenium");
words.put("million" , "quillion");
words.put("million" , "quillion");
words.put("minge" , "punanni");
words.put("minj" , "punanni");
words.put("missing" , "not in da house");
words.put("money" , "mula");
words.put("moron" , "chief");
words.put("most" , "mostest");
words.put("mother" , "mam");
words.put("motor" , "auto");
words.put("muff" , "punanni");
words.put("mum" , "mam");
words.put("music" , "tunes");
words.put("muslim" , "catholics");
words.put("my" , "me");
words.put("nasty" , "rank");
words.put("nazies" , "commies");
words.put("nazy" , "commy");
words.put("neighbourhood" , "turf");
words.put("neighbours" , "homies");
words.put("nice" , "wicked");
words.put("nicest" , "fittest");
words.put("nigger" , "bruver");
words.put("northside" , "westside");
words.put("nuts" , "balls");
words.put("ok" , "wicked");
words.put("old" , "batty");
words.put("organisation" , "crew");
words.put("other" , "udder");
words.put("paddy" , "muslim");
words.put("partner" , "bitch");
words.put("peep" , "check");
words.put("penis" , "dong");
words.put("penises" , "mr biggies");
words.put("perfect" , "wicked");
words.put("period" , "blob");
words.put("person" , "main man");
words.put("pig" , "bitch");
words.put("pisser" , "bog");
words.put("pleasure" , "sweet bitching");
words.put("police" , "constalubury");
words.put("poof" , "batty boy");
words.put("poofter" , "batty boy");
words.put("pop" , "speed garage");
words.put("pork" , "bone");
words.put("porked" , "boned");
words.put("positely" , "for real");
words.put("pouf" , "batty boy");
words.put("pound" , "squid");
words.put("prefer" , "dig");
words.put("pregnant" , "preggers");
words.put("pregnant" , "up da spout");
words.put("prepare" , "make");
words.put("prepared" , "made");
words.put("present" , "in da house");
words.put("pretty" , "fit");
words.put("prison" , "inside");
words.put("probe" , "check");
words.put("prostitute" , "ho");
words.put("protestant" , "muslim");
words.put("protestants" , "muslims");
words.put("pub" , "boozer");
words.put("pussy" , "punanni");
words.put("queen" , "main bitch");
words.put("queer" , "batty boy");
words.put("queers" , "batty boys");
words.put("quick" , "quicrest");
words.put("quid" , "squid");
words.put("rac" , "ruc");
words.put("racism" , "racalist");
words.put("racist" , "racalist");
words.put("racists" , "racalists");
words.put("really" , "for real");
words.put("relax" , "chill");
words.put("relaxation" , "chillin");
words.put("rest" , "chill");
words.put("ride" , "bang");
words.put("ripe" , "full bush");
words.put("rock" , "speed garage");
words.put("rocks" , "is wicked");
words.put("rotten" , "mingin");
words.put("row" , "ruk");
words.put("rows" , "ruks");
words.put("RUC" , "RAC");
words.put("sad" , "down");
words.put("schedule" , "sex life");
words.put("school" , "scool");
words.put("scientist" , "skientist");
words.put("scotland" , "wales");
words.put("screw" , "bone");
words.put("search" , "check");
words.put("see" , "check");
words.put("seek" , "check");
words.put("seen" , "checked");
words.put("seeya" , "bo");
words.put("see-ya" , "bo");
words.put("sell" , "borrow");
words.put("semen" , "orange juice");
words.put("sensi" , "erbal remedy");
words.put("sentences" , "lingo");
words.put("service" , "mend");
words.put("sex" , "riding the punanni");
words.put("sexier" , "fitter");
words.put("sexiest" , "fittest");
words.put("sexy" , "fit");
words.put("shag" , "ride the punanni");
words.put("shagged" , "boned");
words.put("shagger" , "boner");
words.put("shagging" , "ride the punanni");
words.put("shaven" , "shaven haven");
words.put("sheep" , "aminal");
words.put("shit" , "plop");
words.put("shitter" , "bog");
words.put("shout" , "bang");
words.put("shouting" , "bangin");
words.put("situation" , "deal");
words.put("situation" , "story");
words.put("skank" , "erbal remedy");
words.put("skilled" , "brainiest");
words.put("slack" , "chill");
words.put("slag" , "bitch");
words.put("slag" , "mingin bitch");
words.put("sleep" , "go to me julie");
words.put("slut" , "mingin bitch");
words.put("smell" , "stink");
words.put("smells" , "stinks");
words.put("smelly" , "stinkin");
words.put("smiley" , "cheeky");
words.put("speak" , "bang");
words.put("speaking" , "natterin");
words.put("specif" , "pacific");
words.put("specifically" , "pacifically");
words.put("speed" , "speeden");
words.put("sperm" , "orange juice");
words.put("spliff" , "erbal remedy");
words.put("spunk" , "orange juice");
words.put("squad" , "crew");
words.put("staines" , "me turf");
words.put("stare" , "check");
words.put("strange" , "batty");
words.put("stress" , "aggro");
words.put("study" , "hang");
words.put("studying" , "hangin");
words.put("stupid" , "bit thick");
words.put("suffer" , "moan");
words.put("suffers" , "moans");
words.put("support" , "help");
words.put("sweet" , "wicked");
words.put("swiss" , "batty");
words.put("talk" , "natter");
words.put("talking" , "bangin");
words.put("team" , "crew");
words.put("techno" , "speed garage");
words.put("technology" , "bits");
words.put("teenage" , "half bush");
words.put("teenager" , "half bush");
words.put("terrorism" , "terrerorism");
words.put("terrorist" , "terrerorist");
words.put("terrorist" , "terrerorists");
words.put("test" , "da test");
words.put("thanks" , "big up");
words.put("thanks" , "fanks");
words.put("that" , "dat");
words.put("thats" , "dats");
words.put("that's" , "innit");
words.put("the" , "da");
words.put("they" , "dey");
words.put("thick" , "bit thick");
words.put("thing" , "fing");
words.put("things" , "fings");
words.put("this" , "dis");
words.put("thousand" , "quillion");
words.put("timetable" , "sex life");
words.put("tired" , "wrecked");
words.put("tit" , "babylon");
words.put("tittie" , "babylon");
words.put("toilet" , "bog");
words.put("tool" , "dong");
words.put("town" , "turf");
words.put("trillion" , "quillion");
words.put("trouble" , "aggro");
words.put("truck" , "auto");
words.put("truly" , "for real");
words.put("tv" , "telly");
words.put("twat" , "punanni");
words.put("ugliest" , "mingiest");
words.put("ugly" , "mingin");
words.put("uncle" , "uncle jamal");
words.put("uncommonly" , "for real");
words.put("unsexy" , "mingiest");
words.put("unwind" , "chill");
words.put("upset" , "down");
words.put("urinate" , "do a piss");
words.put("urinated" , "did a piss");
words.put("urinates" , "does a piss");
words.put("urinating" , "doing a piss");
words.put("vagina" , "flange");
words.put("very" , "well");
words.put("wales" , "the biggest dick in da ocean");
words.put("wank" , "crack one off");
words.put("wanked" , "cracked one off");
words.put("wanking" , "cracking one off");
words.put("wanks" , "cracks one off");
words.put("want" , "dig");
words.put("weed" , "erbal remedy");
words.put("welcome" , "hear me now, dis is");
words.put("wench" , "bitch");
words.put("westside" , "staines");
words.put("whales" , "da biggest dick in the ocean");
words.put("what" , "wot");
words.put("what's" , "wus");
words.put("whore" , "ho");
words.put("wife" , "bitch");
words.put("willy" , "mr biggy");
words.put("with" , "wiv");
words.put("woman" , "bitch");
words.put("women" , "wimin");
words.put("wonderful" , "wicked");
words.put("words" , "lingo");
words.put("work" , "wurk");
words.put("worker" , "main man");
words.put("workers" , "boys");
words.put("yes" , "aye");
words.put("you" , "yous");
words.put("you're" , "yous is");
words.put("youth" , "youf");
words.put("yugoslavia" , "Newgoslavia");

phrases.put("jerk off" , "crack one off");
phrases.put("haven't" , "ain't");
phrases.put("hasn't" , "ain't");
phrases.put("have not" , "ain't");
phrases.put("has not" , "ain't");
phrases.put("have never" , "ain't never");
phrases.put("has never" , "ain't never");
phrases.put("am gay" , "like it up both pipes");
phrases.put("is gay" , "likes it up both pipes");
phrases.put("well done" , "big up");
phrases.put("pleased to meet you" , "big up to you");
phrases.put("have sex" , "get jiggy");
phrases.put("has sex" , "bones");
phrases.put("having sex" , "riding the punanni");
phrases.put("listen to me" , "hear me now");
phrases.put("isnt it" , "innit");
phrases.put("isn't it" , "innit");
phrases.put("that's right" , "innit");
phrases.put("what's up" , "whaddup");
phrases.put("had" , "did have");
phrases.put("i heard" , "me crew told me");
phrases.put("i hear" , "word on da street");
phrases.put("girl friend" , "bitch");
phrases.put("i want" , "me would dig");
phrases.put("i like" , "me would dig");
phrases.put("that's correct" , "innit");
phrases.put("i live in" , "me turf is");
phrases.put("i'm from" , "me turf is");
phrases.put("a ride" , "fit");
phrases.put("boy friend" , "main man");
phrases.put("disc jockey" , "selecta");
phrases.put("disk jockey" , "selecta");
phrases.put("are you gay" , "do you like it up both pipes");
phrases.put("backdoor burgler" , "batty boy");
phrases.put("im from" , "me turf is");
phrases.put("i come from" , "me turf is");
phrases.put("make love" , "bone");
phrases.put("what's up" , "wussup");
phrases.put("whats up" , "wassup");
phrases.put("good looking" , "fit");
phrases.put("a joint" , "some erbal remedy");
phrases.put("a spliff" , "some erbal remedy");
phrases.put("a bent" , "a batty boy");
phrases.put("tonight" , "a bit later on");
phrases.put("smoking" , "toking");
phrases.put("smokes" , "tokes");
phrases.put("working" , "hangin");
phrases.put("meeting" , "hangin");
phrases.put("colleagues" , "crew");
phrases.put("a smoke" , "a bit of erbal remedy");
phrases.put("pissed off" , "aggro");
phrases.put("im going home" , "me is heading westside");
phrases.put("i'm going home" , "me is heading westside");
phrases.put("my home" , "westside");
phrases.put("anal sex" , "batty boning");
phrases.put("fuck off" , "chill");
phrases.put("shut up" , "chill");
phrases.put("go home" , "head westside");
phrases.put("the hood" , "staines");
phrases.put("what are you talking about" , "wot is yous bangin on about");
phrases.put("i don't know" , "me don't have a clue");
phrases.put("night club" , "cukabilly");
phrases.put("disco" , "cukabilly");
phrases.put("sinn fein" , "muslims");
phrases.put("first class" , "the most bestest");
phrases.put("class a" , "the most bestest");
phrases.put("blow job" , "sweet mr biggy lovin");
phrases.put("i like you" , "would you dig to get jiggy wiv mr biggy");
phrases.put("i love you" , "would you dig to get jiggy wiv mr biggy");
phrases.put("i fancy you" , "would you dig to get jiggy wiv mr biggy");
phrases.put("like to have sex" , "dig to get jiggy wiv mr biggy");
phrases.put("how are you feeling" , "is you wicked");
phrases.put("make love" , "ride the punanni");
phrases.put("my bed" , "the sack");
phrases.put("big one" , "mr biggy");
phrases.put("where do you live" , "where is yous turf");
phrases.put("good looking" , "fit");
phrases.put("going home" , "going westside");
phrases.put("making love" , "riding the punanni");
phrases.put("made love" , "boned");
phrases.put("west side" , "me turf");
phrases.put("a break" , "a chill pill");
phrases.put("what time is it" , "keep it real and tell me da time");
phrases.put("channel 4" , "telly");
phrases.put("laid" , "jiggy");
phrases.put("how do you do" , "is you wicked");
phrases.put("how are you" , "is you wicked");
phrases.put("how's it going" , "is you wicked");
phrases.put("give me a ring" , "gimme a shout");
phrases.put("i find you" , "i fink you is");
phrases.put("Where do I live" , "where is me turf");
phrases.put("what plans" , "what's the deal");
phrases.put("oral sex" , "drinking from the bearded cup");
phrases.put("have fun" , "chill");
phrases.put("a pay rise" , "mo mula");
phrases.put("are you going out" , "is you goin out to check some bitches");
phrases.put("to the pub" , "down the boozer");
phrases.put("looking at" , "checkin out");
phrases.put("i feel like" , "i fink i will be");
phrases.put("he feels like" , "he finks he will be");
phrases.put("she feels like" , "she finks she will be");
phrases.put("that's not right" , "dat ain't right");
phrases.put("slag off" , "dis");
phrases.put("slags off" , "disses");
phrases.put("slagged off" , "dissed");
phrases.put("have a piss" , "do a piss");
phrases.put("has a piss" , "does a piss");
phrases.put("had a piss" , "did a piss");
phrases.put("having a piss" , "doing a piss");
phrases.put("slagging off" , "dissing");
phrases.put("welcome to" , "hear me now, dis is");
}

}